name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Select latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.0.1

      - name: Show selected toolchain
        run: |
          xcodebuild -version
          swift --version

      - name: Build unsigned app
        run: |
          xcodebuild \
            -project Kenpachi.xcodeproj \
            -scheme Kenpachi \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            -derivedDataPath ${{ runner.temp }}/derivedData \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -skipMacroValidation

      - name: Package IPA
        run: |
          mkdir -p ${{ runner.temp }}/Payload
          cp -r ${{ runner.temp }}/derivedData/Build/Products/Release-iphoneos/Kenpachi.app ${{ runner.temp }}/Payload/
          cd ${{ runner.temp }}
          zip -r Kenpachi.ipa Payload
          cd -

      - name: Upload ipa
        uses: actions/upload-artifact@v4
        with:
          name: Kenpachi
          path: ${{ runner.temp }}/Kenpachi.ipa
